import { SYNC_TABLES, type SyncRows } from '../../src/schemas/catalog'

const DOLLAR_TAG = '$catalog$'

export interface CatalogSqlOptions {
  prune: boolean
  /**
   * Rows to upsert, table by table. Leave it out to write the whole catalog; pass the rows that
   * actually differ and the file shrinks from a couple of hundred kilobytes to a few, which is
   * the difference between a file you can read before running it and one you cannot.
   */
  changed?: Partial<SyncRows>
}

/**
 * Builds one transaction that upserts rows of the catalog (and optionally deletes rows missing
 * from data/). Meant for the Supabase SQL editor when no secret key is at hand.
 * Rows go through jsonb_populate_recordset, so values are never spliced into SQL text.
 */
export function catalogToSql(rows: SyncRows, { prune, changed }: CatalogSqlOptions): string {
  const lines = [
    '-- Generated by scripts/sync-supabase.ts --sql. Do not edit; regenerate from data/.',
    changed
      ? '-- Only the rows that differ from the database as it was read.'
      : '-- The whole catalog.',
    'begin;',
    '',
  ]

  for (const table of SYNC_TABLES) {
    // Prune still needs every id of the table, so the deletes below read `rows`, not `changed`.
    const list = changed ? (changed[table] ?? []) : rows[table]
    if (list.length === 0) continue
    const json = JSON.stringify(list)
    if (json.includes(DOLLAR_TAG)) throw new Error(`${table}: data contains ${DOLLAR_TAG}`)
    const columns = Object.keys(list[0]!)
    const updates = columns
      .filter((column) => column !== 'id')
      .map((column) => `${column} = excluded.${column}`)
      .join(', ')
    lines.push(
      `insert into public.${table} (${columns.join(', ')})`,
      `select ${columns.join(', ')}`,
      `from jsonb_populate_recordset(null::public.${table}, ${DOLLAR_TAG}${json}${DOLLAR_TAG}::jsonb)`,
      `on conflict (id) do update set ${updates};`,
      '',
    )
  }

  if (prune) {
    for (const table of [...SYNC_TABLES].reverse()) {
      const ids = rows[table].map((row) => row.id)
      const json = JSON.stringify(ids)
      lines.push(
        `delete from public.${table} where not (id = any (array(select jsonb_array_elements_text(${DOLLAR_TAG}${json}${DOLLAR_TAG}::jsonb))));`,
      )
    }
    lines.push('')
  }

  lines.push('commit;', '')
  return lines.join('\n')
}
